services:
  database:
    image: mysql:5.7
    volumes:
        - ./scripts:./CREATE.sql
    ports: 
        - "3306:3306"  

  application:
    image: spring-boot-image
    build:
      dockerfile: ./part2/Dockerfile
    depends_on:
    - database
    ports:
    - "8080:8080"
